import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
//import 'pages/farmer/community.dart';
import 'pages/farmer/learning_page.dart';


import 'firebase_options.dart'; // generated by `flutterfire configure`

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const FarmingApp());
}

class FarmingApp extends StatelessWidget {
  const FarmingApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Farm Connect',
      theme: ThemeData(
        primaryColor: const Color(0xFF388E3C),
        primarySwatch: Colors.green,
        fontFamily: 'Inter',
        scaffoldBackgroundColor: const Color(0xFFF0F4F8),
        appBarTheme: const AppBarTheme(
          elevation: 0,
          backgroundColor: Colors.transparent,
          titleTextStyle: TextStyle(
            color: Color(0xFF212121),
            fontSize: 22,
            fontWeight: FontWeight.bold,
          ),
          iconTheme: IconThemeData(color: Color(0xFF212121)),
        ),
      ),
      //home: const FarmerCommunityPage(),
      home: const LearningPage(),
      debugShowCheckedModeBanner: false,
    );
  }
}
